# Generated by Django 2.1 on 2018-09-06 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_categories_feedback_logs_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subject',
            new_name='Subjects',
        ),
    ]
