# Generated by Django 2.1 on 2018-09-06 16:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180906_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='dateCreate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
