# Generated by Django 2.1 on 2018-09-06 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_subject_datecreate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categorie',
            new_name='Category',
        ),
    ]
