# Generated by Django 2.1 on 2018-09-07 01:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20180906_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='shortName',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
