# Generated by Django 2.1.2 on 2018-10-16 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_subject_shortname'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=500)),
                ('realname', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('role', models.IntegerField()),
            ],
        ),
    ]
